name: Build and Release Topo

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build ${{ matrix.os }} (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          # Windows universal (GNU)
          - os: windows-latest
            target: x86_64-pc-windows-gnu

          # macOS Intel
          - os: macos-latest
            target: x86_64-apple-darwin

          # macOS Apple Silicon
          - os: macos-latest
            target: aarch64-apple-darwin

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build release binary
        run: |
          cd topo
          cargo build --release --target ${{ matrix.target }}

      - name: Rename binary for release
        run: |
          cd topo/target/${{ matrix.target }}/release
          BIN_NAME="lagarto"
          EXT=""
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            EXT=".exe"
          fi
          mv "topo$EXT" "${BIN_NAME}-${{ matrix.target }}$EXT"
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: topo/target/${{ matrix.target }}/release/lagarto-${{ matrix.target }}*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release with unique tag
        uses: softprops/action-gh-release@v2
        with:
          tag_name: topo-${{ steps.date.outputs.date }}
          name: topo-${{ steps.date.outputs.date }}
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
